apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
    meta.helm.sh/release-name: jellyfin
    meta.helm.sh/release-namespace: jellyfin
    rollme: kknQZ
  creationTimestamp: "2022-11-07T12:15:55Z"
  generation: 4
  labels:
    app.kubernetes.io/instance: jellyfin
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/version: 10.8.6
    helm-revision: "4"
    helm.sh/chart: jellyfin-11.0.44
  name: jellyfin
  namespace: jellyfin
  resourceVersion: "9752218"
  uid: 79c6d771-283a-412c-83aa-c0ab6a28d083
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: jellyfin
      app.kubernetes.io/name: jellyfin
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: jellyfin
        app.kubernetes.io/name: jellyfin
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - laptop1
      containers:
      - env:
        - name: UMASK
          value: "2"
        - name: UMASK_SET
          value: "2"
        - name: S6_READ_ONLY_ROOT
          value: "1"
        - name: NVIDIA_VISIBLE_DEVICES
          value: void
        - name: TZ
          value: UTC
        - name: JELLYFIN_PublishedServerUrl
          value: https://jellyfin.szymonrichert.pl/
        image: szymonrychu/jellyfin:master-0.0.6
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8096
          timeoutSeconds: 5
        name: jellyfin
        ports:
        - containerPort: 8096
          name: main
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8096
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
        startupProbe:
          failureThreshold: 60
          initialDelaySeconds: 10
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8096
          timeoutSeconds: 2
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /cache
          name: cache
        - mountPath: /config
          name: config
        - mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
          name: libcuda
        - mountPath: /media/movies
          name: movies
        - mountPath: /media/music
          name: music
        - mountPath: /dev/nvidia-modeset
          name: nvidia-modeset
        - mountPath: /dev/nvidia0
          name: nvidia0
        - mountPath: /dev/nvidia1
          name: nvidia1
        - mountPath: /dev/nvidiactl
          name: nvidiactl
        - mountPath: /dev/nvram
          name: nvram
        - mountPath: /shared
          name: shared
        - mountPath: /dev/shm
          name: shm
        - mountPath: /tmp
          name: temp
        - mountPath: /config/transcoding-temp
          name: transcoding
        - mountPath: /media/tvseries
          name: tvseries
        - mountPath: /var/logs
          name: varlogs
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      dnsPolicy: ClusterFirst
      enableServiceLinks: false
      initContainers:
      - command:
        - /bin/sh
        - -c
        - |
          /bin/bash <<'EOF'
          echo "Automatically correcting permissions..."

          EOF
        image: tccr.io/truecharts/multi-init:1.1.0@sha256:4337af9c2b79b8d571e4ada3c76de55aff8302632cce91b52af860d4a6607742
        imagePullPolicy: IfNotPresent
        name: prepare
        resources:
          limits:
            cpu: "4"
            memory: 4Gi
          requests:
            cpu: 200m
            memory: 256Mi
        securityContext:
          runAsUser: 0
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 1000
        runAsUser: 1000
        supplementalGroups:
        - 568
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 10
      volumes:
      - emptyDir: {}
        name: cache
      - hostPath:
          path: /k8s-data/jellyfin-config
          type: ""
        name: config
      - hostPath:
          path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
          type: ""
        name: libcuda
      - hostPath:
          path: /k8s-data/disk/movies
          type: ""
        name: movies
      - hostPath:
          path: /k8s-data/disk/music
          type: ""
        name: music
      - hostPath:
          path: /dev/nvidia-modeset
          type: ""
        name: nvidia-modeset
      - hostPath:
          path: /dev/nvidia0
          type: ""
        name: nvidia0
      - hostPath:
          path: /dev/nvidia1
          type: ""
        name: nvidia1
      - hostPath:
          path: /dev/nvidiactl
          type: ""
        name: nvidiactl
      - hostPath:
          path: /dev/nvram
          type: ""
        name: nvram
      - emptyDir: {}
        name: shared
      - emptyDir:
          medium: Memory
        name: shm
      - emptyDir: {}
        name: temp
      - hostPath:
          path: /k8s-data/jellyfin-transcoding-temp
          type: ""
        name: transcoding
      - hostPath:
          path: /k8s-data/disk/tvseries
          type: ""
        name: tvseries
      - emptyDir: {}
        name: varlogs
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-11-07T12:15:55Z"
    lastUpdateTime: "2022-11-07T13:25:40Z"
    message: ReplicaSet "jellyfin-66b5884df5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-12-03T03:09:34Z"
    lastUpdateTime: "2022-12-03T03:09:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
