apiVersion: v2
name: bazarr
description: A Helm chart for Kubernetes
type: application
version: 0.0.2
# renovate: image=ghcr.io/hotio/bazarr
appVersion: release-1.4.2
dependencies:
  - name: oauth2proxy
    version: 0.0.4
    import-values: []
    repository: https://szymonrychu.github.io/selfhosted-kubernetes-charts