---
{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) (eq (.Values.persistence.config.type | default "pvc") "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.config.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
{{- if .Values.persistence.config.storageClass }}
{{- if (eq "-" .Values.persistence.config.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.config.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.persistence.movies.enabled (not .Values.persistence.movies.existingClaim) (eq (.Values.persistence.movies.type | default "pvc") "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-movies
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.movies.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.movies.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.movies.size | quote }}
{{- if .Values.persistence.movies.storageClass }}
{{- if (eq "-" .Values.persistence.movies.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.movies.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.persistence.tvshows.enabled (not .Values.persistence.tvshows.existingClaim) (eq (.Values.persistence.tvshows.type | default "pvc") "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-tvshows
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.tvshows.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.tvshows.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.tvshows.size | quote }}
{{- if .Values.persistence.tvshows.storageClass }}
{{- if (eq "-" .Values.persistence.tvshows.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.tvshows.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.persistence.music.enabled (not .Values.persistence.music.existingClaim) (eq (.Values.persistence.music.type | default "pvc") "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "jellyfin.fullname" . }}-music
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.music.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "jellyfin.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.music.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.music.size | quote }}
{{- if .Values.persistence.music.storageClass }}
{{- if (eq "-" .Values.persistence.music.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.music.storageClass }}"
{{- end }}
{{- end }}
{{- end }}