apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}
  labels: {{- include "eclipse-mosquitto.labels" . | nindent 4 }}
data:
  mosquitto.conf: {{- toYaml .Values.config | nindent 2 }}
    persistence_location /mosquitto/data/
{{- if and .Values.authentication.passwordEntries .Values.authentication.passwordFilePath }}
    password_file /etc/mosquitto/passwordfile
{{- end }}
{{- if and .Values.authorization.acls .Values.authorization.aclfilePath }}
    acl_file /etc/mosquitto/aclfile
{{- end }}