{{- if or .Values.authentication.passwordEntries .Values.authorization.acls }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}
  labels: {{- include "eclipse-mosquitto.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.authentication.passwordEntries }}
  passwordfile: {{ .Values.authentication.passwordEntries | b64enc | quote }}
  {{- end }}
  {{- if .Values.authorization.acls }}
  aclfile: {{ .Values.authorization.acls | b64enc | quote }}
  {{- end }}
{{- end }}