apiVersion: v1
kind: Service
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}
  labels: {{- include "eclipse-mosquitto.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
  {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
  {{- with .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.service.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
{{- with .Values.ports }}
  ports:
  {{- range $key, $value := . }}
    - name: {{ $key }}
      port: {{ $value.port }}
    {{- if $value.nodePort }}
      nodePort: {{ $value.nodePort }}
    {{- end }}
      targetPort: {{ $key }}
      protocol: {{ default "TCP" $value.protocol }}
  {{- end }}
{{- end }}
{{- if .Values.monitoring.enabled }}
    - name: http-metrics
      port: 9234
      targetPort: http-metrics
      protocol: TCP
{{- end }}
  selector: {{- include "eclipse-mosquitto.selectorLabels" . | nindent 4 }}