# Default values for oauth2proxy.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

clientId: test
redirectUrl: https://test.example.com/oauth2/callback
realmUrl: https://test.example.com/realms/master
cookieName: oauth2-authorization-cookie
cookieDomain: test.example.com
clientSecret: test
cookieSecret: test
allowedGroups: "*"
upstreamPort: "8080"

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  pullPolicy: IfNotPresent
  # renovate: image=quay.io/oauth2-proxy/oauth2-proxy
  tag: v7.5.1

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

service:
  type: ClusterIP
  port: 4180