---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-server.fullname" . }}-entrypointd
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
data: 
  00-init-user.sh: |
    #!/bin/bash
    set -euo nounset

    mkdir -p /home/${USER_NAME}/.ssh

    if [[ ! -e "/home/${USER_NAME}/.gnupg" ]]; then
      gpg --import /secrets/private.rsa
    fi
    if [[ ! -e "/home/${USER_NAME}/.ssh/id_rsa" ]]; then
      cp --remove-destination /secrets/id_rsa "/home/${USER_NAME}/.ssh/id_rsa"
    fi
    if [[ ! -e "/home/${USER_NAME}/.ssh/id_rsa.pub" ]]; then
      cp --remove-destination /secrets/id_rsa.pub "/home/${USER_NAME}/.ssh/id_rsa.pub"
    fi
    if [[ ! -e "/home/${USER_NAME}/.ssh/known_hosts" ]]; then
      cp --remove-destination /secrets/known_hosts "/home/${USER_NAME}/.ssh/known_hosts"
    fi
{{- range $name, $content := .Values.extraEntrypointScripts -}}
  {{ $name | nindent 2 }}: |
    {{- $content | nindent 4 }}
{{- end }}