{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.persistence.sharedData.existingClaim | default (printf "%s-%s" (include "code-server.fullname" .) "shared-data")  }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.sharedData.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "code-server.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.persistence.sharedData.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.sharedData.size | quote }}
{{- if .Values.persistence.sharedData.storageClass }}
{{- if (eq "-" .Values.persistence.sharedData.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.sharedData.storageClass }}"
{{- end }}
{{- end }}
{{- end }}