---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server.fullname" . }}-code-secrets
  labels:
    {{- include "code-server.labels" . | nindent 4 }}
type: Opaque
data:
  id_rsa: {{ .Values.config.privateKey | b64enc | quote }}
  id_rsa.pub: {{ .Values.config.publicKey | b64enc | quote }}
  known_hosts: {{ .Values.config.knownHosts | b64enc | quote }}
  private.rsa: {{ .Values.config.gpgEncryptionKey | b64enc | quote }}
{{- range $name, $content := .Values.extraSecrets -}}
  {{ $name | nindent 2 }}: {{ $content | b64enc | quote }}
{{- end }}
