{{- if .Values.oauth2Proxy.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
data:
  keycloak-redirect-url: {{ .Values.oauth2Proxy.keycloakRedirectmUrl }}
  keycloak-realm-url: {{ .Values.oauth2Proxy.keycloakRealmUrl }}
  cookie-name: {{ .Values.oauth2Proxy.cookieName }}
  cookie-domain: {{ .Values.oauth2Proxy.cookieDomain }}
{{- end }}