{{- if .Values.vpnContainer.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
type: Opaque
data:
  qbittorrent-username: {{ .Values.vpnContainer.qbittorrent.username | b64enc | quote }}
  qbittorrent-password: {{ .Values.vpnContainer.qbittorrent.password | b64enc | quote }}
  pia-username: {{ .Values.vpnContainer.privateInternetAccess.username | b64enc | quote }}
  pia-password: {{ .Values.vpnContainer.privateInternetAccess.password | b64enc | quote }}
{{-  end }}
