{{- if .Values.oauth2Proxy.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak-client-id: {{ .Values.oauth2Proxy.keycloakClientId | b64enc | quote }}
  keycloak-client-secret: {{ .Values.oauth2Proxy.keycloakClientSecret | b64enc | quote }}
  cookie-secret: {{ .Values.oauth2Proxy.cookieSecret | b64enc | quote }}
{{- end }}
