---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-server-oauth2.fullname" . }}
  labels:
    {{- include "code-server-oauth2.labels" . | nindent 4 }}
data:
  code-domain: {{ .Values.config.codeServer.domain }}
  keycloak-redirect-url: {{ .Values.config.oauth2Proxy.keycloakRedirectmUrl }}
  keycloak-realm-url: {{ .Values.config.oauth2Proxy.keycloakRealmUrl }}
  cookie-name: {{ .Values.config.oauth2Proxy.cookieName }}
  cookie-domain: {{ .Values.config.oauth2Proxy.cookieDomain }}