---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-server-oauth2.fullname" . }}
  labels:
    {{- include "code-server-oauth2.labels" . | nindent 4 }}
data:
  code-domain: {{ .Values.config.domain | quote }}
  redirect-url: {{ .Values.oauth2Proxy.config.redirectUrl | quote }}
  realm-url: {{ .Values.oauth2Proxy.config.realmUrl | quote }}
  cookie-name: {{ .Values.oauth2Proxy.config.cookieName | quote }}
  cookie-domain: {{ .Values.oauth2Proxy.config.cookieDomain | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "code-server-oauth2.fullname" . }}-entrypointd
  labels:
    {{- include "code-server-oauth2.labels" . | nindent 4 }}
data: 
  00-init-user.sh: |
    #!/bin/bash
    set -euo nounset

    if [[ ! -e "/home/${USER_NAME}/.gnupg" ]]; then
      gpg --import /secrets/private.rsa
    fi

    if [[ ! -e "/home/${USER_NAME}/.ssh" ]]; then
      mkdir -p /home/${USER_NAME}/.ssh
      if [[ ! -e "/home/${USER_NAME}/.ssh/id_rsa" ]]; then
        cp /secrets/id_rsa "/home/${USER_NAME}/.ssh/id_rsa"
      fi
      if [[ ! -e "/home/${USER_NAME}/.ssh/id_rsa.pub" ]]; then
        cp /secrets/id_rsa.pub "/home/${USER_NAME}/.ssh/id_rsa.pub"
      fi
      if [[ ! -e "/home/${USER_NAME}/.ssh/known_hosts" ]]; then
        cp /secrets/known_hosts "/home/${USER_NAME}/.ssh/known_hosts"
      fi
    fi
    chmod 0600 "/home/${USER_NAME}/.gnupg"
    chmod 0600 "/home/${USER_NAME}/.ssh/id_rsa"
{{- range $name, $content := .Values.extraEntrypointScripts -}}
  {{ $name | nindent 2 }}: |
    {{- $content | nindent 4 }}
{{- end }}