apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "code-server-oauth2.fullname" . }}
  labels:
    {{- include "code-server-oauth2.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "code-server-oauth2.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "code-server-oauth2.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "code-server-oauth2.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: code
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: GROUP_NAME
              value: {{ .Values.config.groupName | quote }}
            - name: USER_NAME
              value: {{ .Values.config.userName | quote }}
            - name: USER_UID
              value: {{ .Values.config.userUid | quote }}
            - name: USER_GID
              value: {{ .Values.config.userGid | quote }}
            - name: PROXY_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: code-domain
            - name: GROUP_NAME
              value: "users"
            - name: USER_NAME
              value: {{ .Values.config.userName | quote }}
            - name: USER_UID
              value: {{ .Values.config.userUid | quote }}
            - name: USER_GID
              value: {{ .Values.config.userGid | quote }}
          volumeMounts:
            - mountPath: /home/{{ .Values.config.userName }}
              name: shared-data
            - name: code-secrets
              mountPath: "/secrets"
              readOnly: true
            - name: entrypointd
              mountPath: "/etc/codeserver.d"
              readOnly: true
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.oauth2Proxy.resources | nindent 12 }}
        - name: proxy
          securityContext:
            {{- toYaml .Values.oauth2Proxy.securityContext | nindent 12 }}
          image: "{{ .Values.oauth2Proxy.image.repository }}:{{ .Values.oauth2Proxy.image.tag }}"
          imagePullPolicy: {{ .Values.oauth2Proxy.image.pullPolicy }}
          resources:
            {{- toYaml .Values.oauth2Proxy.resources | nindent 12 }}
          env:
            - name: OAUTH2_PROXY_PROVIDER
              value: keycloak-oidc
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: 0.0.0.0:4180
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: "true"
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
            - name: OAUTH2_PROXY_UPSTREAMS
              value: http://localhost:8080
            - name: OAUTH2_PROXY_SESSION_COOKIE_MINIMAL
              value: "true"
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: client-secret
            - name: OAUTH2_PROXY_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: redirect-url
            - name: OAUTH2_PROXY_ALLOWED_GROUP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: allowed-group
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: realm-url
            - name: OAUTH2_PROXY_COOKIE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: cookie-name
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: cookie-domain
            - name: OAUTH2_PROXY_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: scope
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "code-server-oauth2.fullname" . }}
                  key: cookie-secret
          ports:
            - name: oauth2-http
              containerPort: 4180
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: oauth2-http
          readinessProbe:
            tcpSocket:
              port: oauth2-http
          resources:
            {{- toYaml .Values.oauth2Proxy.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: entrypointd
          configMap:
            name: {{ include "code-server-oauth2.fullname" . }}-entrypointd
        - name: code-secrets
          secret:
            secretName: {{ include "code-server-oauth2.fullname" . }}-code-secrets
        - name: shared-data
        {{- if .Values.persistence.sharedData.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.sharedData.existingClaim | default (printf "%s-%s" (include "code-server-oauth2.fullname" .) "shared-data") }}
        {{- else }}
          emptyDir: {}
        {{- end }}
