---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server-oauth2.fullname" . }}
  labels:
    {{- include "code-server-oauth2.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.oauth2Proxy.config.clientId | b64enc | quote }}
  client-secret: {{ .Values.oauth2Proxy.config.clientSecret | b64enc | quote }}
  cookie-secret: {{ .Values.oauth2Proxy.config.cookieSecret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server-oauth2.fullname" . }}-code-secrets
  labels:
    {{- include "code-server-oauth2.labels" . | nindent 4 }}
type: Opaque
data:
  id_rsa: {{ .Values.config.privateKey | b64enc | quote }}
  id_rsa.pub: {{ .Values.config.publicKey | b64enc | quote }}
  known_hosts: {{ .Values.config.knownHosts | b64enc | quote }}
  private.rsa: {{ .Values.config.gpgEncryptionKey | b64enc | quote }}
