---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server-oauth2.fullname" . }}
  labels:
    {{- include "code-server-oauth2.labels" . | nindent 4 }}
type: Opaque
data:
  keycloak-client-id: {{ .Values.config.oauth2Proxy.keycloakClientId | b64enc | quote }}
  keycloak-client-secret: {{ .Values.config.oauth2Proxy.keycloakClientSecret | b64enc | quote }}
  cookie-secret: {{ .Values.config.oauth2Proxy.cookieSecret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "code-server-oauth2.fullname" . }}-code-secrets
  labels:
    {{- include "code-server-oauth2.labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.secrets.kubeconfig | b64enc | quote }}
  id_rsa: {{ .Values.secrets.privateKey | b64enc | quote }}
  id_rsa.pub: {{ .Values.secrets.publicKey | b64enc | quote }}
  known_hosts: {{ .Values.secrets.knownHosts | b64enc | quote }}
  private.rsa: {{ .Values.secrets.gpgEncryptionKey | b64enc | quote }}
