---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "bitmagnet.fullname" . }}
  labels:
    {{- include "bitmagnet.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not .Values.database.usernameSecret }}
  dbusername: {{ .Values.database.username | b64enc | quote }}
{{- end }}
{{- if not .Values.database.passwordSecret }}
  dbpassword: {{ .Values.database.password | b64enc | quote }}
{{- end }}
{{- if .Values.tmdb.enabled }}
{{- if not .Values.tmdb.apiKeySecret }}
  tmdb-api-key: {{ .Values.tmdb.apiKey | b64enc | quote }}
{{- end }}
{{- end }}
