apiVersion: v2
name: code-server-oauth2
description: A Helm chart for Kubernetes
type: application
version: 1.0.2
# renovate: image=ghcr.io/szymonrychu/code-server
appVersion: 2.1.5
dependencies:
  - name: oauth2proxy
    version: 0.0.4
    import-values: []
    repository: https://szymonrychu.github.io/selfhosted-kubernetes-charts