---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ubuntu-apt-autoupgrade.fullname" . }}
  labels:
    {{- include "ubuntu-apt-autoupgrade.labels" . | nindent 4 }}
data: 
  update.sh: |
{{- .Values.upgradeScript | nindent 4 }}