apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "ubuntu-apt-autoupgrade.fullname" . }}
  labels:
    {{- include "ubuntu-apt-autoupgrade.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ubuntu-apt-autoupgrade.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ubuntu-apt-autoupgrade.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        nameservers:
          - 1.1.1.1
      serviceAccountName: {{ include "ubuntu-apt-autoupgrade.serviceAccountName" . }}
      securityContext:
        allowPrivilegeEscalation: true
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: main
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
          args:
            - /config/update.sh
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: root
              mountPath: "/host-root"
            - name: config
              mountPath: "/config"
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ template "ubuntu-apt-autoupgrade.fullname" . }}
        - name: root
          hostPath:
            path: /