---
{{- if and .Values.persistence.movies.enabled (not .Values.persistence.movies.existingClaim) (eq (.Values.persistence.movies.type | default "pvc") "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "ffmpeg-encoder-daemon.fullname" . }}-movies
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.movies.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "ffmpeg-encoder-daemon.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.movies.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.movies.size | quote }}
{{- if .Values.persistence.movies.storageClass }}
{{- if (eq "-" .Values.persistence.movies.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.movies.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
---
{{- if and .Values.persistence.tvshows.enabled (not .Values.persistence.tvshows.existingClaim) (eq (.Values.persistence.tvshows.type | default "pvc") "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "ffmpeg-encoder-daemon.fullname" . }}-tvshows
  namespace: {{ .Release.Namespace }}
{{- with .Values.persistence.tvshows.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "ffmpeg-encoder-daemon.selectorLabels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.tvshows.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.tvshows.size | quote }}
{{- if .Values.persistence.tvshows.storageClass }}
{{- if (eq "-" .Values.persistence.tvshows.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistence.tvshows.storageClass }}"
{{- end }}
{{- end }}
{{- end }}