annotations:
  category: Infrastructure
apiVersion: v2
appVersion: 0.12.1-debian-11-r11
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.x
description: MetalLB is a load-balancer implementation for bare metal Kubernetes clusters, using standard routing protocols.
engine: gotpl
home: https://github.com/bitnami/charts/tree/master/bitnami/metallb
icon: https://bitnami.com/assets/stacks/metallb-speaker/img/metallb-speaker-stack-220x234.png
keywords:
  - load-balancer
  - balancer
  - lb
  - bgp
  - arp
  - vrrp
  - vip
maintainers:
  - email: cellebyte@gmail.com
    name: cellebyte
  - name: Bitnami
    url: https://github.com/bitnami/charts
name: metallb
sources:
  - https://github.com/metallb/metallb
  - https://github.com/bitnami/containers/tree/main/bitnami/metallb
  - https://metallb.universe.tf
version: 4.0.0
