---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
data:
{{- if not .Values.redis.hostConfigMap }}
  redis: {{ ( printf "redis://%s:6379" ( tpl .Values.redis.host . )) | quote }}
{{- end }}
{{- if not .Values.database.hostConfigMap }}
  dbhost: {{ ( tpl .Values.database.host . ) | quote }}
{{- end }}
{{- if not .Values.database.portConfigMap }}
  dbport: {{ .Values.database.port | quote }}
{{- end }}
{{- if not .Values.database.nameConfigMap }}
  dbname: {{ (tpl .Values.database.name . ) | quote }}
{{- end }}