{{- if .Values.gotenbergTika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-gotenberg
  labels:
    {{- include "paperless-ngx.gotenbergLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paperless-ngx.gotenbergSelectorLabels" . | nindent 4 }}
{{- end }}
