---
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not .Values.database.usernameSecret }}
  dbusername: {{ .Values.database.username | b64enc | quote }}
{{- end }}
{{- if not .Values.database.passwordSecret }}
  dbpassword: {{ .Values.database.password | b64enc | quote }}
{{- end }}
{{- if not .Values.admin.usernameSecret }}
  admin-username: {{ .Values.admin.username | b64enc | quote }}
{{- end }}
{{- if not .Values.admin.passwordSecret }}
  admin-password: {{ .Values.admin.password | b64enc | quote }}
{{- end }}
{{- if not .Values.admin.emailSecret }}
  admin-email: {{ .Values.admin.email | b64enc | quote }}
{{- end }}
