{{- if .Values.gotenbergTika.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-tika
  labels:
    {{- include "paperless-ngx.tikaLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "paperless-ngx.tikaSelectorLabels" . | nindent 4 }}
{{- end }}
