---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
data:
{{- range $env_name, $env_value := .Values.env }}
  {{ $env_name }}: {{ $env_value | quote}}
{{- end }}
