apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "samba.fullname" . }}
  labels:
    {{- include "samba.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "samba.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.upgradeStrategy }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "samba.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "samba.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.initPermissions.enabled }}
        - name: init-permissions
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          restartPolicy: Always
          command:
            - /bin/sh
          args:
            - -c
            - |
              su -c chown -R "$(id -u):$(id -g)" /mounts/*/
          resources:
            {{- toYaml .Values.initPermissions.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: true
          volumeMounts:
            - name: documents
              mountPath: /mounts/documents
            - name: movies
              mountPath: /mounts/movies
            - name: tvshows
              mountPath: /mounts/tvshows
            - name: music
              mountPath: /mounts/music
        {{- end }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/bash
          args:
            - /usr/bin/samba.sh
          ports:
            - name: samba1
              containerPort: 137
              protocol: UDP
            - name: samba2
              containerPort: 138
              protocol: UDP
            - name: samba3
              containerPort: 139
              protocol: TCP
            - name: samba4
              containerPort: 445
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: samba4
            timeoutSeconds: 5
          startupProbe:
            failureThreshold: 60
            initialDelaySeconds: 10
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: samba4
            timeoutSeconds: 2
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "samba.fullname" . }}
          # env:
          #   - name: GLOBAL1
          #     value: tls enabled=no
          #   - name: GLOBAL2
          #     value: bind interfaces only = yes
          #   - name: USERID
          #     value: {{ ( (.Values.securityContext | default .Values.podSecurityContext).runAsUser | default 0) | quote }}
          #   - name: GROUPID
          #     value: {{ ( (.Values.securityContext | default .Values.podSecurityContext).runAsGroup | default 0) | quote }}
          #   - name: PERMISSIONS
          #     value: 644:644
          #   - name: NMDP
          #     value: "true"
          #   - name: RECYCLE
          #     value: "true"
          #   - name: SHARE1
          #     value: media;/media;yes;no;yes
          #   - name: TZ
          #     value: UTC
          volumeMounts:
            - name: cache
              mountPath: /cache
            - name: varlogs
              mountPath: /var/log/samba
            - name: tmp
              mountPath: /tmp
            - name: movies
              mountPath: /media/movies
            - name: tvshows
              mountPath: /media/tvshows
            - name: music
              mountPath: /media/music
            - name: documents
              mountPath: /media/documents
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      hostNetwork: true
      volumes:
        - name: cache
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: temp
          emptyDir: {}
        - name: varlogs
          emptyDir: {}
        - name: movies
        {{- if .Values.persistence.movies.enabled }}
          {{- if eq (.Values.persistence.movies.type | default "pvc") "pvc" -}}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.movies.existingClaim | default (printf "%s-%s" (include "samba.fullname" .) "movies")  }}
          {{- else if eq .Values.persistence.movies.type "hostPath" }}
          hostPath:
            path: {{ .Values.persistence.movies.hostPath }}
          {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: tvshows
        {{- if .Values.persistence.tvshows.enabled }}
          {{- if eq (.Values.persistence.tvshows.type | default "pvc") "pvc" -}}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.tvshows.existingClaim | default (printf "%s-%s" (include "samba.fullname" .) "tvshows")  }}
          {{- else if eq .Values.persistence.tvshows.type "hostPath" }}
          hostPath:
            path: {{ .Values.persistence.tvshows.hostPath }}
          {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: music
        {{- if .Values.persistence.music.enabled }}
          {{- if eq (.Values.persistence.music.type | default "pvc") "pvc" -}}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.music.existingClaim | default (printf "%s-%s" (include "samba.fullname" .) "music")  }}
          {{- else if eq .Values.persistence.music.type "hostPath" }}
          hostPath:
            path: {{ .Values.persistence.music.hostPath }}
          {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: documents
        {{- if .Values.persistence.documents.enabled }}
          {{- if eq (.Values.persistence.documents.type | default "pvc") "pvc" -}}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.documents.existingClaim | default (printf "%s-%s" (include "samba.fullname" .) "documents")  }}
          {{- else if eq .Values.persistence.documents.type "hostPath" }}
          hostPath:
            path: {{ .Values.persistence.documents.hostPath }}
          {{- end }}
        {{- else }}
          emptyDir: {}
        {{- end }}
