{{- range .Values.persistence }}
---
{{- if and .enabled (not .existingClaim) (eq (.type | default "pvc") "pvc") }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "samba.fullname" $ }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
{{- with .annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    {{- include "samba.selectorLabels" $ | nindent 4 }}
spec:
  accessModes:
    - {{ .accessMode | quote }}
  resources:
    requests:
      storage: {{ .size | quote }}
{{- if .storageClass }}
{{- if (eq "-" .storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .storageClass }}"
{{- end }}
{{- end }}
{{- end }}
{{- end }}