# Default values for oauth2proxy-external.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/oauth2-proxy/oauth2-proxy
  pullPolicy: IfNotPresent
  tag: ""

externalAddress: https://google.com

redirectUrl: https://test.example.com/oauth2/callback
# redirectUrlConfigmap: "name/key"
# redirectUrlSecret: "name/key"
realmUrl: https://test.example.com/realms/master
# realmUrlConfigmap: "name/key"
# realmUrlSecret: "name/key"
cookieName: oauth2-authorization-cookie
# cookieNameConfigmap: "name/key"
# cookieNameSecret: "name/key"
cookieDomain: test.example.com
# cookieDomainConfigmap: "name/key"
# cookieDomainSecret: "name/key"
allowedGroups: "*"
# allowedGroupsConfigmap: "name/key"
# allowedGroupsSecret: "name/key"

additionalDNS:
  nameservers:
    - 192.168.1.1
  searches:
    - local
  options: []
    # - name: ndots
    #   value: "2"
    # - name: edns0

clientId: test
# clientIdSecret: "name/key"
clientSecret: test
# clientSecretSecret: "name/key"
cookieSecret: test
# cookieSecretSecret: "name/key"

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi


service:
  type: ClusterIP
  port: 80

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local


nodeSelector: {}

tolerations: []

affinity: {}
