---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "esphome.fullname" . }}
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
data: 
  dashboard_use_ping: {{ .Values.config.dashboard_use_ping | quote }}
  dashboard_relative_url: {{ .Values.config.dashboard_relative_url | quote }}
  disable_ha_authentication: {{ .Values.config.disable_ha_authentication | quote }}
{{- if .Values.oauth2proxy.enabled }}
  redirect-url: {{ .Values.oauth2proxy.config.redirectUrl | quote }}
  realm-url: {{ .Values.oauth2proxy.config.realmUrl | quote }}
  cookie-name: {{ .Values.oauth2proxy.config.cookieName | quote }}
  cookie-domain: {{ .Values.oauth2proxy.config.cookieDomain | quote }}
  allowed-group: {{ .Values.oauth2proxy.config.allowedGroup | quote }}
{{- end }}
