apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "esphome.fullname" . }}
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "esphome.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "esphome.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "esphome.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: esphome
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          env:
            - name: HOME
              value: /config
      {{- if (not .Values.oauth2proxy.enabled) }}
            - name: USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: username
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: password
      {{- end }}
            - name: ESPHOME_DASHBOARD_USE_PING
              valueFrom:
                configMapKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: dashboard_use_ping
            - name: ESPHOME_DASHBOARD_RELATIVE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: dashboard_relative_url
            - name: DISABLE_HA_AUTHENTICATION
              valueFrom:
                configMapKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: disable_ha_authentication
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: "/config"
      {{- if .Values.oauth2proxy.enabled }}
        - name: oauth2proxy
          securityContext:
            {{- toYaml .Values.oauth2proxy.securityContext | nindent 12 }}
          image: "{{ .Values.oauth2proxy.image.repository }}:{{ .Values.oauth2proxy.image.tag }}"
          imagePullPolicy: {{ .Values.oauth2proxy.image.pullPolicy }}
          resources:
            {{- toYaml .Values.oauth2proxy.resources | nindent 12 }}
          env:
            - name: OAUTH2_PROXY_PROVIDER
              value: keycloak-oidc
            - name: OAUTH2_PROXY_HTTP_ADDRESS
              value: 0.0.0.0:4180
            - name: OAUTH2_PROXY_REVERSE_PROXY
              value: "true"
            - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
              value: "true"
            - name: OAUTH2_PROXY_UPSTREAMS
              value: http://localhost:{{ .Values.service.port }}
            - name: OAUTH2_PROXY_SESSION_COOKIE_MINIMAL
              value: "true"
            - name: OAUTH2_PROXY_EMAIL_DOMAINS
              value: "*"
            - name: OAUTH2_PROXY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: client-id
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: client-secret
            - name: OAUTH2_PROXY_REDIRECT_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: redirect-url
            - name: OAUTH2_PROXY_ALLOWED_GROUP
              valueFrom:
                configMapKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: allowed-group
            - name: OAUTH2_PROXY_OIDC_ISSUER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: realm-url
            - name: OAUTH2_PROXY_COOKIE_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: cookie-name
            - name: OAUTH2_PROXY_COOKIE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: cookie-domain
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "esphome.fullname" . }}
                  key: cookie-secret
          ports:
            - name: oauth2-http
              containerPort: 4180
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: oauth2-http
          readinessProbe:
            tcpSocket:
              port: oauth2-http
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "esphome.fullname" .) }}
      {{- else }}
          emptyDir: {}
      {{- end -}}
