---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esphome.fullname" . }}
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.config.username | b64enc | quote }}
  password: {{ .Values.config.password | b64enc | quote }}