---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "esphome.fullname" . }}
  labels:
    {{- include "esphome.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.oauth2proxy.enabled }}
  client-id: {{ .Values.oauth2proxy.config.clientId | b64enc | quote }}
  client-secret: {{ .Values.oauth2proxy.config.clientSecret | b64enc | quote }}
  cookie-secret: {{ .Values.oauth2proxy.config.cookieSecret | b64enc | quote }}
{{- else }}
  username: {{ .Values.config.username | b64enc | quote }}
  password: {{ .Values.config.password | b64enc | quote }}
{{- end }}