{{- $fullname := include "db-provision.fullname" . -}}
{{- $name     := include "db-provision.name" . -}}
{{- $chart    := include "db-provision.chart" . -}}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ $fullname }}-secrets
  labels:
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ $chart }}
type: Opaque
data:
  {{- if not .Values.database.userSecret }}
  database-user: {{ .Values.database.user | b64enc | quote }}
  {{- end }}

  {{- if not .Values.database.passwordSecret }}
  database-password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}

  {{- if not .Values.provision.passwordSecret }}
  provision-password: {{ .Values.provision.password | b64enc | quote }}
  {{- end }}
