---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "filebrowser-oauth2.fullname" . }}
  labels:
    {{- include "filebrowser-oauth2.labels" . | nindent 4 }}
data:
  redirect-url: {{ .Values.oauth2proxy.config.redirectUrl | quote }}
  realm-url: {{ .Values.oauth2proxy.config.realmUrl | quote }}
  cookie-name: {{ .Values.oauth2proxy.config.cookieName | quote }}
  cookie-domain: {{ .Values.oauth2proxy.config.cookieDomain | quote }}