---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  inputs.yaml: |
{{ .Values.config | toYaml | indent 4 }}
{{- range $fname, $fcontents := .Values.templates }}
  {{ $fname }}.j2: {{ $fcontents | toYaml | indent 2 }}
{{- end }}