---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data: 
  configuration.yaml: |
{{- .Values.config | toYaml | nindent 4 }}
  init.sh: |
{{- .Values.initScript | nindent 4 }}