---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-templates
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
{{- range $fname, $fcontents := .Values.templates }}
  {{ $fname }}.jinja2: {{ $fcontents | toYaml | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-values
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ .Values.config | toYaml | indent 4 }}
{{- if .Values.config.postgresql.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  postgresql-host: {{ .Values.config.postgresql.host | quote }}
  postgresql-port: {{ .Values.config.postgresql.port | quote }}
{{- end }}