---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}-templates
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
{{- range $fname, $fcontents := .Values.templates }}
  {{ $fname }}.jinja2: {{ $fcontents | toYaml | indent 2 }}
{{- end }}
{{- if .Values.postgresql.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data:
  host: {{ .Values.postgresql.host | quote }}
  port: {{ .Values.postgresql.port | quote }}
{{- end }}