---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data: 
  config.yaml.j2: |
{{- .Values.configuration_template | nindent 4 }}
  variables.yaml: |
{{- .Values.config | toYaml | nindent 4 }}