---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
data: 
  config.yaml.j2: |
{{- .Values.configuration_template | nindent 4 }}
  automations.yaml: ""
  zone.yaml: ""
  sensor.yaml: ""
  switch.yaml: ""
  device_tracker.yaml: ""
  variables.yaml: |
{{- .Values.config | toYaml | nindent 4 }}