apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "home-assistant.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      dnsConfig:
        nameservers:
          {{- toYaml .Values.additionalDNSServers | nindent 10 }}
      serviceAccountName: {{ include "home-assistant.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
          {{- range $fname, $fcontents := .Values.templates }}
        - name: config-{{ $fname }}
          securityContext:
            {{- toYaml $.Values.initSecurityContext | nindent 12 }}
          image: "{{ $.Values.initConfig.image.repository }}:{{ $.Values.initConfig.image.tag }}"
          imagePullPolicy: {{ $.Values.initConfig.image.pullPolicy }}
          args:
            - /templates/{{ $fname }}.j2
            - /templates/inputs.yaml
            - -o
            - /config/{{ $fname }}
          resources:
            {{- toYaml $.Values.initResources | nindent 12 }}
          env:
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  {{- if $.Values.zalandoPostgresql.enabled }}
                  name: homeassistant.home-assistant-db.credentials.postgresql.acid.zalan.do
                  key: username
                  {{- else }}
                  name: {{ include "home-assistant.fullname" $ }}
                  key: postgresql_username
                  {{- end }}
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if $.Values.zalandoPostgresql.enabled }}
                  name: homeassistant.home-assistant-db.credentials.postgresql.acid.zalan.do
                  key: password
                  {{- else }}
                  name: {{ include "home-assistant.fullname" $ }}
                  key: postgresql_password
                  {{- end }}
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "home-assistant.fullname" $ }}
                  key: influxdb_token
          volumeMounts:
            - name: config-template
              mountPath: /templates
              readOnly: true
            - name: config
              mountPath: "/config"
          {{- end }}
          {{- if .Values.initWaitForPostgres.enabled }}
        - name: wait-for-db
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.initWaitForPostgres.image.repository }}:{{ .Values.initWaitForPostgres.image.tag }}"
          imagePullPolicy: {{ .Values.initWaitForPostgres.image.pullPolicy }}
          resources:
            {{- toYaml .Values.initWaitForPostgres.resources | nindent 12 }}
          command:
            - /usr/local/bin/bash
          args:
            - -c
            - |
                echo "Waiting for ${POSTGRES_HOST}:${POSTGRES_PORT}"
                while ! timeout 1 bash -c "cat < /dev/null > /dev/tcp/${POSTGRES_HOST}/${POSTGRES_PORT}"; do
                  sleep 1
                  echo "."
                done
                echo "OK"
          env:
            - name: POSTGRES_HOST
              value: {{ .Values.config.postgresql.host }}
            - name: POSTGRES_PORT
              value: {{ .Values.config.postgresql.port | quote }}
          {{- end }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - sh
              args:
                - -c
                - |
                  [[ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8123)" == "200" ]]
            initialDelaySeconds: 1
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
                - sh
              args:
                - -c
                - |
                  [[ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8123)" == "200" ]]
            initialDelaySeconds: 1
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PATH_TO_YOUR_CONFIG
              value: /config/configuration.yaml
            - name: TZ
              value: "Poland"
          volumeMounts:
            - name: config
              mountPath: "/config"
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-template
          configMap:
            name: {{ template "home-assistant.fullname" . }}
        - name: config
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "home-assistant.fullname" .) }}
      {{- else }}
          emptyDir: {}
      {{- end -}}
      {{- if .Values.extraVolumes }}
{{ tpl .Values.extraVolumes . | indent 6 }}
      {{- end }}
