{{- if .Values.zalandoPostgresql.enabled -}}
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: {{ include "home-assistant.fullname" . }}-db
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
  {{- with .Values.zalandoPostgresql.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  teamId: homeassistant
  numberOfInstances: 1
  users:
    superuser:
    - superuser
    - createdb
    homeassistant: []
  enableMasterLoadBalancer: false
  enableReplicaLoadBalancer: false
  enableConnectionPooler: false
  enableReplicaConnectionPooler: false
  databases:
    homeassistant: homeassistant
  postgresql:
    version: "14"
    parameters:  # Expert section
      shared_buffers: "32MB"
      max_connections: "60"
      log_statement: "all"
  volume:
    size: {{ .Values.zalandoPostgresql.persistence.size | quote }}
  {{- if (eq "-" .Values.zalandoPostgresql.persistence.storageClass) }}
    storageClass: ""
  {{- else }}
    storageClass: "{{ .Values.zalandoPostgresql.persistence.storageClass }}"
  {{- end }}
  enableShmVolume: true
  resources:
{{- toYaml .Values.zalandoPostgresql.resources | nindent 4 }}
  maintenanceWindows:
    - 01:00-06:00  #UTC
    - Sat:00:00-04:00
{{- end }}
