---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not (.Values.zalandoPostgresql.enabled) }}
  postgresql_username: {{ .Values.config.postgresql.username | quote | b64enc }}
  postgresql_password: {{ .Values.config.postgresql.password | quote | b64enc }}
{{- end }}
  influxdb_token: {{ .Values.config.influxdb.token | quote | b64enc }}
  prometheus_token: {{ .Values.config.prometheus.token | quote | b64enc }}