---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
type: Opaque
data:
{{- if .Values.postgresql.enabled }}
{{- if not (.Values.postgresql.usernameSecret) }}
  username: {{ .Values.postgresql.username | b64enc | quote }}
{{- end }}
{{- if not (.Values.postgresql.passwordSecret) }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
{{- end }}
{{- end }}
{{- if .Values.prometheus.enabled }}
  prometheus_token: {{ .Values.prometheus.token | b64enc | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}-values
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ (include "home-assistant.config" . ) | b64enc | quote }}