---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
type: Opaque
data:
  secrets.yaml: {{ .Values.secrets | toYaml | b64enc | quote }}
