{{- if .Values.config.localVoiceProcessing.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}-openwakeword
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    ha-component: openwakeword
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 10400
      targetPort: oupw-http
      protocol: TCP
      name: oupw-http
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
    ha-component: openwakeword
{{- end }}
