apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if .Values.metrics.token }}
    - port: 8080
      targetPort: tcp-proxy
      protocol: TCP
      name: tcp-proxy
{{- end }}
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
