{{- if .Values.metrics.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "home-assistant.fullname" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: 60s
    path: /api/prometheus
    port: tcp-proxy
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
{{- end }}