{{- if .Values.localVoiceProcessing.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "home-assistant.fullname" . }}-piper
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    ha-component: piper
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 10200
      targetPort: piper-http
      protocol: TCP
      name: piper-http
  selector:
    {{- include "home-assistant.selectorLabels" . | nindent 4 }}
    ha-component: piper
{{- end }}
