apiVersion: v2
name: home-assistant
description: A Helm chart for Kubernetes
type: application
version: 0.9.0

# renovate: image=ghcr.io/home-assistant/home-assistant
appVersion: "2023.11.3"

dependencies:
- condition: config.influxdb.enabled
  name: influxdb
  version: 5.10.2
  repository: https://charts.bitnami.com/bitnami
