{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "gha-runner.fullname" . }}
  labels:
    {{- include "gha-runner.labels" . | nindent 4 }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "gha-runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}