---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gha-runner.fullname" . }}
  labels:
    {{- include "gha-runner.labels" . | nindent 4 }}
data:
  github-owner: {{ .Values.config.githubOwner | quote }}
  github-repository: {{ .Values.config.githubRepository | quote }}