---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gha-runner.fullname" . }}
  labels:
    {{- include "gha-runner.labels" . | nindent 4 }}
type: Opaque
data:
  github-personal-token: {{ .Values.config.githubPersonalToken | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gha-runner.fullname" . }}-runtime-secrets
  labels:
    {{- include "gha-runner.labels" . | nindent 4 }}
type: Opaque
data:
  id_rsa: {{ .Values.secrets.privateKey | b64enc | quote }}
  id_rsa.pub: {{ .Values.secrets.publicKey | b64enc | quote }}
  known_hosts: {{ .Values.secrets.knownHosts | b64enc | quote }}
  private.rsa: {{ .Values.secrets.gpgEncryptionKey | b64enc | quote }}
