{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gha-runner.serviceAccountName" . }}
  labels:
    {{- include "gha-runner.labels" . | nindent 4 }}
automountServiceAccountToken: true
{{- end }}