---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flood-rtorrent.fullname" . }}
  labels:
    {{- include "flood-rtorrent.labels" . | nindent 4 }}
type: Opaque
data:
  client-id: {{ .Values.oauth2proxy.config.clientId | b64enc | quote }}
  client-secret: {{ .Values.oauth2proxy.config.clientSecret | b64enc | quote }}
  cookie-secret: {{ .Values.oauth2proxy.config.cookieSecret | b64enc | quote }}