---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2proxy-external.fullname" . }}
  labels:
    {{- include "oauth2proxy-external.labels" . | nindent 4 }}
type: Opaque
data:
{{- if not (.Values.clientIdSecret) }}
  client-id: {{ .Values.clientId | b64enc | quote }}
{{- end }}
{{- if not (.Values.clientSecretSecret) }}
  client-secret: {{ .Values.clientSecret | b64enc | quote }}
{{- end }}
{{- if not (.Values.cookieSecretSecret) }}
  cookie-secret: {{ .Values.cookieSecret | b64enc | quote }}
{{- end }}