name: "Merge Succesfull Run"

on:
  workflow_run:
    types:
      - "completed"
    workflows:
      - "Helm Lint"

jobs:
  merge:
    name: "Merge"

    runs-on: "ubuntu-latest"

    if: github.event.workflow_run.conclusion == 'success'

    steps:
      - name: "Request review from @szymonrychu-bot"
        uses: "actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b" # v7
        with:
          github-token: "${{ secrets.SZYMONRYCHU_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            const reviewers = [
              "szymonrychu",
            ]

            await github.rest.pulls.requestReviewers({
              owner: repository.owner,
              repo: repository.repo,
              pull_number: pullRequest.number,
              reviewers: reviewers,
            })

      - name: "Assign @szymonrychu-bot"
        uses: "actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b" # v7
        with:
          github-token: "${{ secrets.SZYMONRYCHU_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            const assignees = [
              "szymonrychu",
            ]

            await github.rest.issues.addAssignees({
              owner: repository.owner,
              repo: repository.repo,
              assignees: assignees,
              issue_number: pullRequest.number
            })

      - name: "Approve pull request"
        uses: "actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b" # v7
        with:
          github-token: "${{ secrets.SZYMONRYCHU_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            await github.rest.pulls.createReview({
              event: "APPROVE",
              owner: repository.owner,
              repo: repository.repo,
              pull_number: pullRequest.number,
            })

      - name: "Merge pull request"
        uses: "actions/github-script@f28e40c7f34bde8b3046d885e986cb6290c5673b" # v7
        with:
          github-token: "${{ secrets.SZYMONRYCHU_TOKEN }}"
          script: |
            const pullRequest = context.payload.workflow_run.pull_requests[0]
            const repository = context.repo

            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: pullRequest.number,
              repo: repository.repo,
            })
